.only-default: &only-default
  only:
    - tags
    - dev
    - master
    - merge_requests

stages:
  - vetting
  - tests

code_quality:
  <<: *only-default
  stage: vetting
  image: golangci/golangci-lint:v1.27
  script: "golangci-lint run --config .golangci.yml"

copyright_notice:
  <<: *only-default
  stage: vetting
  script:
    - .scripts/check-copyright-notice.sh
    - .scripts/check-notice-authors.sh origin/dev

vanity_import:
  <<: *only-default
  stage: vetting
  script: ".scripts/check-vanity-imports.sh $PWD"

unit_tests:
  <<: *only-default
  image: golang
  stage: tests
  script: "go test -timeout 60s -cover ./..."

unit_race_tests:
  <<: *only-default
  image: golang
  stage: tests
  script: "go test -timeout 120s -race -gcflags=all=-d=checkptr=0 ./..."
