.only-default: &only-default
  only:
    - tags
    - pushes
    - merge_requests

stages:
  - vetting
  - tests

before_script:
  - go get -u golang.org/x/lint/golint
  - export GOPATH=$HOME/go
  - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

lint:
  <<: *only-default
  image: golang
  stage: vetting
  script:
    - golint -set_exit_status ./...
  allow_failure: true

vet:
  <<: *only-default
  image: golang
  stage: vetting
  script:
    - go vet ./...

unit_race_tests:  
  image: golang
  stage: tests
  script:
    - go test -race ./...
  only:
    - merge_requests

unit_tests:
  image: golang
  stage: tests
  script:
    - go test -cover ./...
  only:
    - merge_requests

